#!/bin/bash

# Install registration key

regkey=""

if [ -n "$regkey" ]; then
	[[ ! -d /Users/Shared/TechSmith/Snagit ]] && /bin/mkdir -p /Users/Shared/TechSmith/Snagit
	/usr/bin/defaults write /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey RegKey -data "$regkey"
	/usr/bin/plutil -convert xml1 /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist
	/bin/mv /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey
	/bin/chmod -R 777 /Users/Shared/TechSmith
	/bin/chmod a+x /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey
fi

# install config in current user's home folder


PREFS_PLIST="${0%/*}/com.TechSmith.Snagit2018.plist"
CONTAINER_PREFS="/Library/Group Containers/7TQL462TU8.com.techsmith.snagit/Snagit 2018/Preferences"
ERROR=0

function log {
	echo "$1"
	/usr/bin/logger -t "SAPCorp: ${0##*/}" "$1"
}

if [[ -f "$PREFS_PLIST" ]]; then

	# get the currently logged-in user
	CURRENT_USER=$(/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }')

	if [[ -n "$CURRENT_USER" ]]; then

		# get path to user's home directory
		USER_HOME=$(/usr/bin/dscl . -read /Users/$CURRENT_USER NFSHomeDirectory 2>/dev/null | /usr/bin/sed 's/^[^\/]*//g')

		if [[ -d "$USER_HOME" && "$USER_HOME" != "/var/empty" ]]; then

			# import the default preferences
			/usr/bin/defaults import "$USER_HOME/Library/Preferences/${PREFS_PLIST##*/}" "$PREFS_PLIST"
			/usr/sbin/chown -R $CURRENT_USER:staff "$USER_HOME/Library/Preferences/${PREFS_PLIST##*/}"
			/bin/chmod -R 600 "$USER_HOME/Library/Preferences/${PREFS_PLIST##*/}"

			# copy the default prefs to user template
			/bin/cp -f "$PREFS_PLIST" "$3/System/Library/User Template/Non_localized/Library/Preferences/"
			/usr/sbin/chown -R root:wheel "$3/System/Library/User Template/Non_localized/Library/Preferences/${PREFS_PLIST##*/}"
			/bin/chmod -R 600 "$3/System/Library/User Template/Non_localized/Library/Preferences/${PREFS_PLIST##*/}"

			# disable collection of usage data
			if [[ ! -d "$USER_HOME/$CONTAINER_PREFS" ]]; then
				/bin/mkdir -p "$USER_HOME/$CONTAINER_PREFS"
			fi

			/usr/bin/defaults write "$USER_HOME/$CONTAINER_PREFS/7TQL462TU8.com.techsmith.snagit" sendTrackerbirdData -bool NO
			/usr/sbin/chown -R $CURRENT_USER:staff "$USER_HOME/$CONTAINER_PREFS"

			if [[ ! -d "$3/System/Library/User Template/Non_localized/$CONTAINER_PREFS" ]]; then
				/bin/mkdir -p "$3/System/Library/User Template/Non_localized/$CONTAINER_PREFS"
			fi

			/usr/bin/defaults write "$3/System/Library/User Template/Non_localized/$CONTAINER_PREFS/7TQL462TU8.com.techsmith.snagit" sendTrackerbirdData -bool NO

		else
			log "ERROR! Unable to determine path to user's home folder"
			ERROR=1
		fi
	else
		log "ERROR! Unable to determine current user"
		ERROR=1
	fi

else
	log "ERROR! Install files not found"
	ERROR=1
fi

exit $ERROR