#!/bin/bash

ERROR=0

# Install registration key

regkey=""

if [ -n "$regkey" ]; then
	[[ ! -d "/Users/Shared/TechSmith" ]] && /bin/mkdir "/Users/Shared/TechSmith"
	[[ ! -d "/Users/Shared/TechSmith/Camtasia" ]] && /bin/mkdir "/Users/Shared/TechSmith/Camtasia"
	/usr/bin/defaults write "/Users/Shared/TechSmith/Camtasia/Camtasia Registration Key Unified License" RegKey -data "$regkey"
	/usr/bin/plutil -convert xml1 "/Users/Shared/TechSmith/Camtasia/Camtasia Registration Key Unified License.plist"
	/bin/mv "/Users/Shared/TechSmith/Camtasia/Camtasia Registration Key Unified License.plist" "/Users/Shared/TechSmith/Camtasia/Camtasia Registration Key Unified License"
	/bin/chmod -R 777 "/Users/Shared/TechSmith"
	/bin/chmod a+x "/Users/Shared/TechSmith/Camtasia Registration Key Unified License"
fi

exit $ERROR
